steps:
- name: 'node:lts-alpine3.12'
  entrypoint: 'npm'
  args: ['install']
  dir: 'app/angular'
- name: 'node:lts-alpine3.12'
  entrypoint: 'npm'
  args: ['run','dev-build']
  dir: 'app/angular'
- name: 'gcr.io/cloud-builders/gcloud'
  dir: 'app'
  args: ['-q','app', 'deploy', 'app-dev.yaml']

timeout: "3000s"
